name: Build and Release OpenMow AI

on:
  workflow_dispatch: # manuel start

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.x'
          architecture: 'x64'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Update pubspec.yaml version
        run: |
          BUILD_NUMBER=$(git rev-list --count HEAD)
          VERSION_NAME="1.0.$BUILD_NUMBER"
          sed -i "s/^version: .*/version: $VERSION_NAME+$BUILD_NUMBER/" pubspec.yaml
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Build APK
        run: flutter build apk --release

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION_NAME }}-${{ env.BUILD_NUMBER }}
          name: "OpenMow AI v${{ env.VERSION_NAME }} (Build ${{ env.BUILD_NUMBER }})"
          generate_release_notes: true # adds changes to release log
          files: build/app/outputs/flutter-apk/app-release.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
